import fs from "node:fs";import path from "node:path";import {fileURLToPath} from "node:url";
import {chromium,expect as baseExpect} from "../../src/frontend/node_modules/@playwright/test/index.mjs";
const expect=baseExpect.configure({timeout:45000});
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");const qa=JSON.parse(fs.readFileSync(process.env.EBT_FLOW_QA_ACCESS??path.join(root,"tmp/release/flow-live-qa-access.json"),"utf8"));
if(!qa.syntheticOnly||!qa.email.endsWith("@ebt.example"))throw new Error("Synthetic fixture required");
const url="https://ebt-connect-hml.greenrock-01c2b42d.brazilsouth.azurecontainerapps.io";
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1366,height:900}});const page=await context.newPage();const errors=[];page.on("pageerror",e=>errors.push(e.message));const checks=[];
function check(name,ok){if(!ok)throw new Error(name);checks.push({name,passed:true});console.log("PASS "+name);}
try {
 for(let i=0;i<120;i++){const logo=await context.request.get(url+"/assets/ebt-logo-240.webp");if(logo.status()===200&&logo.headers()["content-type"]?.includes("image/"))break;if(i===119)throw new Error("Published logo asset not ready");await new Promise(resolve=>setTimeout(resolve,5000));}
 check("Published logo asset returns image HTTP 200",true);
 await page.goto(url);await page.getByLabel("E-mail",{exact:true}).fill(qa.email);await page.getByLabel("Senha",{exact:true}).fill(qa.password);await page.getByRole("button",{name:"Entrar",exact:true}).click();await expect(page.getByRole("button",{name:"EBT Flow",exact:true})).toBeVisible();await expect(page.locator(".brand-logo")).toBeVisible();await expect.poll(()=>page.locator(".brand-logo").evaluate(img=>img.naturalWidth)).toBeGreaterThan(0);check("Desktop brand image has positive natural width",true);
 const csrf=await(await context.request.get(url+"/api/security/csrf")).json();const switched=await context.request.post(url+"/api/auth/context/"+qa.tenantA,{headers:{"X-CSRF-TOKEN":csrf.token}});check("Synthetic QA tenant A selected",switched.status()===204);
 await page.reload();await page.getByRole("button",{name:"EBT Flow",exact:true}).click();await expect(page.getByRole("region",{name:"EBT Flow"})).toBeVisible();check("Published Flow opens from application catalog",true);
 const subject="QA navegador publicado "+Date.now();await page.getByLabel("Assunto do protocolo").fill(subject);await page.getByRole("button",{name:"Abrir protocolo",exact:true}).click();
 const row=page.getByRole("article").filter({has:page.getByRole("heading",{name:subject,exact:true})});await expect(row).toBeVisible();check("Protocol created through published UI",true);
 await row.getByRole("button",{name:/Iniciar an/}).click();await expect(row.getByRole("textbox")).toBeVisible();await row.getByRole("textbox").fill("Published browser synthetic result.");await row.getByRole("button",{name:"Concluir protocolo",exact:true}).click();await expect(row.getByText("Conclu\u00eddo",{exact:true})).toBeVisible();check("Start and completion through published UI",true);
 await row.getByRole("button",{name:/Ver hist/}).click();await expect(row.getByText("Published browser synthetic result.",{exact:true})).toBeVisible();check("Persisted result visible in history",true);
 await page.reload();await page.getByRole("button",{name:"EBT Flow",exact:true}).click();await expect(page.getByRole("heading",{name:subject,exact:true})).toBeVisible();check("Browser reload retains protocol",true);
 const screenshots=[];for(const width of [320,390,768,1366]){await page.setViewportSize({width,height:900});check("Published Flow no horizontal overflow "+width,await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));if(width===390||width===1366){const file=`evidencias/flow-online-qa-${width}.png`;await page.screenshot({path:path.join(root,file),fullPage:true,animations:"disabled"});screenshots.push(file);}}
 check("No browser page errors",errors.length===0);
 const report={generatedUtc:new Date().toISOString(),url,version:"0.4.0",passed:true,checks,screenshots,syntheticOnly:true,credentialsSaved:false,visualReview:{reviewed:false,logoAssetAvailable:true,logoNaturalWidthPositive:true},realMessagesSent:0,limits:["User business acceptance remains separate","Screenshots contain only newly provisioned synthetic QA tenant"]};fs.writeFileSync(path.join(root,"evidencias/flow_online_browser_qa_20261009.json"),JSON.stringify(report,null,2)+"\n");
 const file=path.join(root,"evidencias/flow_online_qa_20261009.json");const api=JSON.parse(fs.readFileSync(file,"utf8"));api.browserEvidence="evidencias/flow_online_browser_qa_20261009.json";api.browserPassed=true;fs.writeFileSync(file,JSON.stringify(api,null,2)+"\n");
}catch(error){console.error("FAIL Published live UI smoke after: "+(checks.at(-1)?.name??"initialization")+"; "+String(error.name)+"; "+(String(error.message).includes("strict mode")?"strict locator match":String(error.message).includes("Timeout")?"timeout":"assertion"));if(checks.some(x=>x.name==="Synthetic QA tenant A selected"))await page.screenshot({path:path.join(root,"tmp/release/live-flow-qa-failure.png"),fullPage:true});process.exitCode=1;}finally{await browser.close();}
