"""Conteúdo autoral de organização; especificações candidatas, não código de produto."""

PHASE_CONTEXT = {
'P01': dict(inputs='Árvore local CASST, inventário de fontes e relatórios históricos.',output='Baseline do recorte, mapa de contratos e seleção de reaproveitamento.',refs=['F01','F02','F03','F10','F11','F13','F17','F19','F21','F26'],product='gestao',risk='Extração de versão incompleta ou com direitos de uso pendentes.',exclude='Não executar migração, deploy, envio ou cópia de banco de cliente.'),
'P02': dict(inputs='G0 e componentes selecionados; ambiente EBT sintético.',output='Comandos de build, ambiente QA, CI e fundação observável.',refs=['F02','F04','F05','F06','F14','F16'],product='fundacao',risk='Configuração local oculta ou uso acidental de ambiente de outro cliente.',exclude='Não construir infraestrutura distribuída, Redis ou filas sem necessidade medida.'),
'P03': dict(inputs='G0/G1, marca sintética e base de site escolhida.',output='Site essencial demonstrável, conteúdo e manual de implantação.',refs=['F17','F18','F19','F20'],product='site',risk='Confundir formulário/contacto manual com CRM ou entrega de mensagem.',exclude='Não construir CMS completo, transparência, e-SIC ou portal administrativo novo.'),
'P04': dict(inputs='G1, massa A/B e contrato de identidade do recorte.',output='Sessão, tenant, autorização e auditoria aprovados no recorte.',refs=['F04','F05','F06','F07','F08','F09','F14','F15'],product='seguranca',risk='Fronteira de empresa incorreta, acesso por ID ou cache cruzado.',exclude='Não usar header fornecido pelo cliente como autoridade de tenant; não migrar identidade dos produtos originais.'),
'P05': dict(inputs='G-SEG, cadastro e fluxo comercial mínimo congelados.',output='CRM simples com duas configurações e contratos estáveis.',refs=['F02','F03','F04','F05','F19','F21'],product='crm',risk='Recadastro por módulo, quebra de IDs, idempotência ou histórico.',exclude='Não incluir financeiro, OS, propostas completas, caixa de entrada coletiva ou canais externos automáticos.'),
'P06': dict(inputs='G-SEG/G-CRM, categoria comercial e storage privado de QA.',output='Um fluxo GED privado com versão, revisão e recuperação.',refs=['F03','F14','F15','F22','F23','F24','F25'],product='documentos',risk='Binário exposto, aprovação obsoleta ou backup sem arquivo/chave.',exclude='Não incluir dado clínico, assinatura digital ou liberação ampla sem política de scan.'),
'P07': dict(inputs='G-CRM e G-SEG vigentes; responsável e contato de origem.',output='Tarefas do contato e primeira composição CRM/tarefas do Connect.',refs=['F02','F03','F14'],product='tarefas',risk='Próxima ação solta, fuso incorreto ou indicador sem reconciliação.',exclude='A primeira origem é contato; vínculo documental só após P06. Não adicionar escalonamento externo ou calendário de fornecedor.'),
'P08': dict(inputs='G-SEG/G-GED/G-TASK e especificação do fluxo fixo.',output='Protocolo concorrente/idempotente com histórico de tramitação.',refs=['F26'],product='flow',risk='Número repetido, estado ilegal ou concorrência sobrescrevendo movimento.',exclude='Não implementar designer, regras dinâmicas, W3/W4, timers ou consulta pública.'),
'P09': dict(inputs='G-SEG/G-CRM/G-TASK/G-MSG/G-GED e manifesto do candidato.',output='Pacote reproduzível e demonstração integrada para piloto.',refs=['F07','F08','F18','F20','F22','F25','F26'],product='release',risk='Apresentar código/testes locais como aceite de cliente ou produção.',exclude='Não implantar em produção nem executar operações comerciais reais neste planejamento.'),
'P10': dict(inputs='Defeito/impedimento comprovado em qualquer fase.',output='Correção e prova pertinente ou capacidade não consumida.',refs=['F02','F07','F08','F25'],product='reserva',risk='Consumir reserva em funcionalidade nova ou contar saldo livre como entrega.',exclude='Não usar reserva para ampliar o contrato; manter registro de consumo real.')}

# ID | saída concreta | passos específicos | cenários objetivos | falha a evitar
DETAIL_ROWS = '''
P01-01|Manifesto da árvore-fonte do recorte|Confirmar checkout e status; selecionar arquivos produtores/consumidores; registrar hash, commit e diferença local|Hash reproduzido; untracked pertinente incluído; comparação sem escrita nas fontes|HEAD sozinho omite alterações locais
P01-02|Tabela capacidade/prova/limite por fonte|Ler resultado e horário dos logs; separar reteste conclusivo de falhas anteriores; atribuir local/CI/piloto/produção ao cenário correto|SQL conclusivo separado do anterior; onboarding continua pendente; provas não se estendem a módulos ausentes|Nome final do arquivo usado como certificado
P01-03|Ficha do fluxo CRM de entrada|Escolher cadastro/histórico/próxima ação; listar perfis e eventos; fechar campos mínimos e itens fora do pacote|Uma jornada completa e demonstrável; até cinco etapas do funil; sem requisito financeiro escondido|Fluxo inicial expande para toda a CASST
P01-04|Mapa tela -> API -> regra -> dados|Localizar contratos e endpoints; registrar ID de origem e vínculo; identificar invalidação de cache e efeitos posteriores|Produtor e consumidor concordam; campo e cardinalidade registrados; nenhum endpoint inventado como existente|UI parecida consome recurso diferente
P01-05|Matriz de origem e permissão de uso|Relacionar fonte/autoria/licença do componente; conferir assets e dependências; marcar permissão pendente com impedimento específico|Cada item escolhido tem origem; pendência impede uso comercial daquele item; dado de cliente ausente|Código disponível confundido com direito comercial
P01-06|Registro G0 e fila de PRs|Conferir manifesto/escopo/provas; separar copia segura de extração nova; escrever ordem e critérios dos primeiros PRs|Gate indica passaram/pendências; recorte afetado não inicia vermelho; bases não foram alteradas|Generalização inicia sem baseline recuperável
P02-01|ADR do recorte e fronteiras|Comparar desenho com fonte; decidir monólito modular mínimo; registrar serviços compartilhados e limites de stack|ADR identifica recomendações e decisões ainda abertas; site preserva stack existente; Core não promete C0-C13|Arquitetura força reescrita integral
P02-02|Guia de clone e build|Definir solução e diretórios necessários; documentar ferramentas/versões reais; testar comandos a partir de clone de QA|Build backend e frontend reproduzíveis; arquivo de solução real; sem arquivo privado implícito|Comando referencia solução inexistente
P02-03|Esquema de configuração por ambiente|Listar nomes de opções sem valores privados; validar ausência de opção obrigatória; excluir segredos de código/log|Config ausente falha com mensagem segura; Dev não usa produção; secret não aparece em repositório|Fallback conecta banco de outro cliente
P02-04|Massa A/B documentada|Criar perfis de empresa fictícios; gerar contatos e usuários sintéticos permitidos/proibidos; anotar IDs e casos de conflito|Dados próprios em A/B; cópia de cadastro real ausente; fixtures reproduzíveis|Massa dá prova falsa de isolamento
P02-05|Mapa QA banco/storage|Definir destinos exclusivos; configurar provisionamento de teste; registrar modo de destruir/recriar só o QA autorizado|Destino exclusivo conferido; tentativa com alvo produção recusada; binário e metadado separados|Script de teste toca ambiente existente
P02-06|Cliente HTTP do recorte|Comparar contratos e CSRF de origem; reusar tratamento de 401/erro/download; preservar formulário em falha|401 tratado; erro não vira sucesso; download inválido tem diagnóstico seguro|Nova chamada ignora cliente autenticado
P02-07|CI do recorte e diagnóstico|Montar build/typecheck/testes relevantes; documentar health e correlação; impedir dados sensíveis em logs|CI bloqueia falha real; health representa dependências definidas; traceId não contém cadastro|Health verde mascara dependência crítica
P02-08|Demonstração e ficha G1|Iniciar QA com massa própria; salvar e reler um registro; registrar comandos, resultado e limitações|Health e persistência conferidos; clone reproduz; nada declarado produção|Build apresentado como demonstração completa
P03-01|Ficha de seleção EBT ou CRP|Comparar páginas/canal/admin existente; escolher uma base para este pacote; registrar justificativa e diferenças|Escolha única explícita; source e versão identificados; somente funções comprovadas aproveitadas|Mesclar bases incompatíveis por aparência
P03-02|Configuração de marca do site|Centralizar nome/logo/canais/serviços; usar duas marcas fictícias; conferir origem de texto e foto|Conteúdo muda por config; contato correto por marca; assets autorizados|Foto ou contato real de cliente permanece no template
P03-03|Cinco páginas conectadas|Reusar templates e menus; ajustar home/serviços/sobre/contato/privacidade; manter estados e links existentes|Links e assets válidos; retorno/menu coerentes; layout mobile e desktop|Quantidade de páginas gera páginas vazias
P03-04|Contrato de confirmação de contato|Identificar se é link manual ou formulário servidor; testar confirmação somente após registro; preservar campos em falha|Registro consultável quando aplicável; erro mostra ausência de confirmação; wa.me é descrito como abertura|Mensagem enviada declarada por abertura de link
P03-05|Relatório visual focal do site|Conferir páginas alteradas em celular/computador; testar foco e contraste; verificar proteção de painel existente|Sem overflow externo; teclado alcança controles; visitante não acessa painel privado|Revisão visual ignora rota administrativa
P03-06|Pacote site e manual|Reunir fontes/config/assets licenciados; registrar conteúdo e canal escolhidos; documentar implantação e retorno no ambiente que será definido|Pacote reproduz; checklist de entrada do cliente; publicação futura claramente condicionada|Pacote preparado confundido com site novo online
P04-01|Matriz de acesso candidato|Definir admin/operador/consulta; mapear ação e recurso; explicitar empresa/carteira e apoio técnico|Permissão definida por operação; negativa explícita; técnico não recebe documento restrito automaticamente|Role amplo substitui escopo do recurso
P04-02|Jornada de sessão reaproveitada|Identificar cookie/token da fonte; manter estratégia equivalente; conferir logout, expiração e modo Dev|Sessão válida acessa recorte; expirada é negada; header debug fora de Dev não autentica|Autenticação de desenvolvimento ativa fora de Dev
P04-03|Resolução de empresa confiável|Resolver tenant por identidade/vínculo ativo; recusar tentativa de alteração via cliente; usar contexto único em serviços|Header/body adulterados não trocam empresa; usuário sem vínculo é negado; contexto não deriva de nome visual|TenantId vindo do formulário governa acesso
P04-04|Consultas/gravações com escopo|Aplicar filtros/autorização no servidor; verificar inserts/updates; revisar jobs ou exportações existentes no recorte|A não lê nem escreve B; listagem e ID direto equivalentes; mutação cruzada não persiste|Filtro na UI serve como fronteira de segurança
P04-05|Migration e índices do recorte|Mapear unicidades globais; incluir tenant onde a regra exigir; gerar migration sem reescrever histórico|Banco vazio e snapshot anterior migram; duplicidade no mesmo tenant negada; independência A/B preservada|Novo índice invalida cadastro existente
P04-06|Prova SQL de isolamento|Usar banco QA real e fixtures controladas; rodar leitura/gravação A/B; separar erro de fixture de regra do produto|Leitura cruzada vazia/negada; insert indevido recusado; suíte pertinente verde sem ignorar caso crítico|Erro de setup é contado como proteção funcionando
P04-07|Autorização por recurso|Verificar tenant e escopo do registro carregado; aplicar a download/exportação/consulta; usar resposta que não exponha conteúdo|ID de B negado; operador sem escopo negado; export não amplia carteira|Rota de download contorna listagem protegida
P04-08|Cache contextual e limpeza|Incluir empresa/usuário/perfil em cache pertinente; limpar em mudança de identidade; conferir corrida de resposta antiga|Logout limpa; troca A/B não mostra dado anterior; resposta de contexto antigo descartada|Cache faz vazamento apesar de SQL protegido
P04-09|Evento de auditoria seguro|Reusar evento e identidade do ator; registrar operação/vínculo/correlação; limitar conteúdo antes/depois|Evento após escrita confirmada; erro não fabrica sucesso; senha/token/anexo restrito ausentes|Log duplica dado sensível ou omite autor
P04-10|Conferência de sessão e CSRF|Aplicar controles compatíveis com estratégia escolhida; testar expiração/revogação; conferir cookies ou validação do token|CSRF inválido recusado quando aplicável; sessão revogada negada; headers seguros pertinentes|Misturar requisitos de cookie e JWT sem desenho
P04-11|Onboarding do recorte aprovado|Reproduzir ativação e destino após termo/senha; localizar produtor da navegação/estado; corrigir causa no recorte e testar negativas|Ativação abre tela prevista; token inválido/reutilizado negado; timeout ampliado não substitui correção|Onboarding vermelho escondido por espera maior
P04-12|Ficha G-SEG A/B|Executar matriz de sessão/tenant/perfil; reconciliar SQL e navegador; registrar bloqueios por consumidor|Permitido e negado demonstrados; vazamento bloqueia gate; banco real identificado|Prova unitária substitui teste da fronteira real
P05-01|Contrato canônico de cadastro|Escolher ID interno existente; distinguir pessoa/organização/contato; registrar vínculo por empresa e fontes externas quando existirem|Um ID atravessa telas; matrícula não vira identidade universal; nomes de UI não renomeiam chaves|Pessoa global une clientes sem política
P05-02|Cadastro idempotente do recorte|Reusar normalização/validação; delimitar regra de duplicidade por tenant; conferir repetição e resposta perdida|Mesmo comando não duplica; cadastro recarrega; telefone de B não provoca fusão com A|Normalização gera união automática incorreta
P05-03|Lista e busca contratadas|Reusar tabela/filtros/paginação e conferir contrato; registrar exportação existente/formato/colunas/limite; verificar escopo e estados|Busca formatada encontra dentro do escopo; vazio/erro claros; limites de página respeitados; ID/lista/exportação de B e carteira alheia negados; retorno conserva filtro e seleção; exportação incluída corresponde ao filtro e escopo contratados|R1 mantido apesar de alteração em filtro/autorização
P05-04|Histórico persistido com autoria|Reusar escrita/lista; separar nota interna e contato; preservar data informada e ordem do histórico|Falha mantém texto; conversa antiga não vira última indevidamente; reload preserva autoria|Nota interna contada como conversa comercial
P05-05|Responsável e próxima ação|Validar responsável ativo/no escopo; persistir prazo e descrição; invalidar dados afetados nas telas|Lista e detalhe refletem mesmo valor; responsável indevido negado; ausência de prazo explícita|Salvar atualiza só a tela atual
P05-06|Funil fixo de até cinco etapas|Configurar rótulos sem mudar enums da fonte; persistir mudança/histórico; usar token de versão|Etapa persiste; edição antiga conflita; retorno respeita estados permitidos|Duas pessoas sobrescrevem histórico de etapa
P05-07|Tela configurável de referência|Aplicar identidade/menu/textos de estado; manter APIs/IDs; conferir representação e impressão incluída|Config A/B muda apresentação; operação mantém contrato; sem hard-code CASST no recorte|Troca visual renomeia propriedade persistida
P05-08|Segundo consumidor do CRM|Usar mesmo serviço e componente; configurar empresa sintética diferente; rodar contratos/fluxo e escopo|Mesma regra sem fork; dados separados; correção no componente vale nos dois|Duas cópias passam como Core reutilizável
P05-09|Importação fixa de até 100 contatos QA|Definir layout/lote/hash e chave escopada; validar preview sem persistência final; revalidar permissão e confirmar em transação|Preview não grava; inválido não confirma; reenvio não duplica e resultado por linha existe; mesma chave com conteúdo diferente conflita; duas confirmações e perda de resposta recuperam um resultado; tenant/carteira e permissão revogada impedem commit; falha SQL não deixa gravação parcial|Planilha real importada por inferência
P05-10|Ficha G-CRM e instrução de uso|Demonstrar login/cadastro/histórico/próxima ação; registrar source/config; escrever limites e entrada do cliente|ID único após reload; gate segurança vigente; manual sem prometer integração externa|Demo sintética vira aceite de cliente
P06-01|Ficha da categoria documental|Escolher documento comercial e entidade de origem; definir acesso/revisão/versão; delimitar tipo e tamanho conforme ambiente|Categoria única especificada; vínculo claro; política pendente explícita|Regra clínica inserida no GED comercial
P06-02|Metadado documentado e persistido|Reusar identidade e referência de storage; gravar hash/MIME/tamanho/autor; vincular entidade no tenant|Metadado aponta arquivo correto; vínculo cruzado negado; versão identificada|Hash calculado não corresponde ao binário final
P06-03|Upload com estado pendente|Validar tipo/tamanho e nome seguro; armazenar em destino privado; confirmar só após resposta persistida|Inválido/excesso/path traversal negados; falha não libera; arquivo novo pendente|Arquivo recém-enviado fica público
P06-04|Download autorizado por recurso|Resolver metadado no tenant; conferir direito ao documento; autorizar acesso temporário apenas após verificação|A autorizado baixa; B negado; URL ou key não contorna escopo|Chave do storage vira autorização
P06-05|Revisão e versão imutável|Separar arquivo/versão da decisão; registrar ator/motivo; nova versão exige nova revisão|Versão anterior permanece; rejeição rastreável; aprovação antiga não libera nova versão|Edição silenciosa altera documento aprovado
P06-06|Falha/retry/conflito do GED|Injetar resposta perdida e falha de storage em QA; testar idempotência; simular revisão concorrente|Retry retorna identidade lógica; metadado sem binário não confirma; versão obsoleta conflita|Registro órfão apresentado como upload concluído
P06-07|Restore documental isolado|Capturar banco/arquivos/chaves necessários; recuperar em destino novo; comparar metadados/hash e testar acesso|Integridade ok; arquivo baixado idêntico; chave necessária recuperada; pendência scan mantém restrição|Backup apenas de banco é chamado recuperação completa
P06-08|Ficha G-GED com composição documental|Repetir fluxo documento nos dois contextos; conferir hashes/permissão e restore; ligar documento a tarefa existente sem ampliar acesso|Upload/revisão/download negado e permitido; mesmo componente nos dois; restore preserva versão e hash; vínculo de tarefa/documento respeita origem e permissão A/B|Tarefa é usada como autorização implícita de arquivo
P07-01|Contrato da tarefa vinculada|Mapear tipo de origem e ID; reusar responsável/prazo/estado; definir fechamento e vínculo de empresa|Tarefa aponta cadastro existente; origem preservada; responsável elegível|Tarefa gera segundo cadastro para armazenar contexto
P07-02|Lista de tarefas por escopo|Reusar criação/filtros; ligar contrato; conferir prazo/responsável nos estados de lista|Salvar/reload conferidos; filtro retorna origem correta; acesso negado claro|Mudança funcional passa como ajuste visual
P07-03|Fechamento/cancelamento auditado|Exigir resultado ou motivo pertinente; preservar transições; conferir retry do comando|Conclusão repetida não duplica; cancelamento rastreável; estado indevido recusado|Fechar apaga histórico da pendência
P07-04|Regra temporal de atraso|Persistir instante sem ambiguidade; exibir Brasília; usar relógio controlado e prazo opcional explícito|Virada de dia correta; sem prazo não vira atraso; timezone do host não muda regra|Data local armazenada sem fuso muda vencimento
P07-05|Próxima ação coerente com tarefa|Exibir pendência por usuário; ligar contato/estado à fonte coerente de tarefa; reconciliar fechamento e painel|Painel mostra registro persistido; próxima ação acessível; nenhum envio externo declarado; lista/detalhe/tarefa refletem mesma alteração; conclusão ou cancelamento não conserva pendência indevida|Duas cópias editáveis divergem em prazo/responsável
P07-06|Ficha G-TASK e checkpoint Connect CRM/tarefas|Definir numerador/período/escopo; comparar lista e cartão; demonstrar CRM/tarefas e conferir versão dos gates|Contador bate com lista; filtro/perfil muda contexto; consulta não altera tarefa; mesma identidade percorre CRM e tarefa em A/B após nova sessão; novas operações repetem negativas no G-SEG vigente|Métrica conta registros fora da vigência
P08-01|Especificação do protocolo piloto|Fixar um tipo/ano/tenant; listar campos e transições; definir ator para cada mudança|Fluxo aberto/em análise/concluído definido; numeração única; sem designer|Protótipo recebe requisitos de workflow completo
P08-02|Abertura transacional idempotente|Criar índice/regra de sequência SQL; serializar incremento conforme desenho; vincular chave de operação ao protocolo|Duas criações não repetem número; mesma chave retorna mesmo protocolo; rollback não cria sucesso|Numeração calcula max+1 sem proteção
P08-03|Vínculos de interessado/anexo/responsável|Validar cadastros existentes; ligar documento do tenant; guardar IDs sem duplicar entidade|Inexistente negado; B não vira interessado de A; download mantém política GED|Vínculo contorna fronteira entre módulos
P08-04|Consulta e linha de movimentações|Listar por perfil e sigilo; mostrar detalhes/histórico; manter ator/origem/destino e instante|Consulta por ID de B negada; sigilo coerente; histórico não pode ser reescrito pela UI|Consulta detalhada expõe registro oculto na listagem
P08-05|Transição aberto -> em análise|Validar ator e versão esperada; gravar estado e histórico atomicamente; recusar transição fora da tabela|Ator autorizado avança; consulta não muda; evento e estado são coerentes|Gravar histórico e estado em operações divergentes
P08-06|Encerramento com resultado|Exigir resultado e versão vigente; tornar repetição segura; preservar encerramento para consulta|Sem resultado negado; reenvio não duplica; conflito não sobrescreve decisão|Segunda pessoa altera encerramento confirmado
P08-07|Regressão SQL do fluxo|Executar sucesso/negativo/retry; disputar versão em duas sessões; conferir reload/restart e transação|Número único; histórico consistente; B negado; restart mantém protocolo|Teste em memória substitui concorrência SQL
P08-08|Ficha G-FLOW do fluxo fixo|Demonstrar abertura/anexo/tramitação/conclusão; mostrar histórico e negativa; declarar recursos excluídos|Jornada completa em QA; gate GED vigente; W3/W4 e consulta pública continuam fora|Piloto anunciado como Workflow profissional
P09-01|Manifesto único do candidato|Relacionar commit/arquivos/config; associar cenário ao relatório; registrar resultado e ressalvas por módulo|Todos os recortes rastreáveis; prova temporal preservada; versão exibida concorda|Relatório de um módulo certifica pacote inteiro
P09-02|Jornada integrada contato e tarefas|Executar criação e consulta; percorrer histórico e fechamento da tarefa; conferir mesmo ID em nova sessão|Cadastro único preservado; conclusão persiste; perfil de consulta não escreve|Frontend aprovado sem persistência do resultado
P09-03|Jornada CRM com consumidores A/B|Logar nos perfis; cadastrar/interagir/tarefar; conferir negativa/cadastro único/contrato|Mesmo ID nas telas; outro tenant não lê; duas configurações sem fork|Só usuário admin serve como homologação
P09-04|Jornada comunicação e documento|Receber e responder mensagem; conciliar callbacks e documento do contato; repetir negativas e recuperação|A/B não cruzam mensagem/arquivo; callback/falha não reenvia indevidamente; restore preserva ledger e vínculo|ACK ou status de fila apresentado como entrega
P09-05|Ensaio de atualização e retorno|Migrar snapshot sintético anterior; comparar IDs/contagens/invariantes; executar caminho de recuperação escolhido|Dados preservados; esquema compatível; forward fix ou rollback ensaiado|Downgrade destrutivo usado sem recuperar dados
P09-06|Ensaio restore e incidente QA|Restaurar banco/arquivo/chave em destino separado; iniciar candidato restaurado; emitir diagnóstico sanitizado|Login/consulta/download conferidos; traceId útil; nenhum dado restrito em log|Backup íntegro sem aplicação iniciar é dado como suficiente
P09-07|Manual e ficha de aceite preparada|Registrar escopo/responsáveis/config; instruir operação/retorno; criar campos de aceite do usuário real|Manual completo; campos pendentes explícitos; nenhum aceite preenchido por inferência|Ficha preparada confundida com aceite obtido
P09-08|Fechamento do ciclo e backlog posterior|Reconciliar resultados e esforço; registrar gates e pendências; preservar site/Flow adiados e próximos recortes|180h e consumo reserva claros; canal sem prova mantém gate pendente; produção não declarada|Fim do orçamento tratado como produto completo
P10-01|Registro condicional de correção onboarding|Apontar incidente/caso falho; consumir horas só após trabalho; repetir cenário afetado|Causa e correção registradas; sucesso com mesmo critério; saldo da reserva atualizado|Aumento de timeout oculta defeito
P10-02|Registro condicional de correção SQL/tenant|Isolar caso/fixture/ambiente; corrigir causa no recorte; provar A/B e preservar snapshot|Fixture não mascara falha; migration ensaiada; gate continua bloqueado até prova|Retirar teste de segurança para caber no prazo
P10-03|Registro condicional de desacoplamento|Identificar hard-code/regra copiada; ajustar contrato e config; repetir consumidores A/B|Correção única serve aos dois; origem/versionamento preservados; custo real registrado|Fork por cliente vira solução de reserva
P10-04|Registro condicional de recuperação/storage|Diagnosticar binário/metadado/chave/ambiente; corrigir mínimo; repetir restore/download com hash|Recuperação validada; falha de provedor distinta; autorização de liberação permanece|Trocar provedor por inferência sem homologação
P10-05|Registro condicional de rodada adicional|Selecionar casos afetados por correção; repetir e comparar; registrar aceite pendente e reserva restante|Só casos necessários repetidos; prova tem versão; saldo não consumido permanece reserva|Sobra de hora vira nova funcionalidade sem escopo
'''

def details():
    from comunicacao_planejada import DETAILS, CONTEXT
    PHASE_CONTEXT['P11'] = CONTEXT
    result={}
    for row in (DETAIL_ROWS.strip() + '\n' + DETAILS.strip()).splitlines():
        ident,out,steps,tests,risk=row.split('|')
        assert ident not in result
        result[ident]=dict(saida_concreta=out,passos=[s.strip() for s in steps.split(';')],
            cenarios=[s.strip() for s in tests.split(';')],falha_a_evitar=risk)
    return result
