<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ebt.Application\Ebt.Application.csproj" />
    <ProjectReference Include="..\Ebt.Infrastructure\Ebt.Infrastructure.csproj" />
  </ItemGroup>
</Project>
